//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Web;
using System.Web.Profile;
using System.Configuration;
using System.Web.Security;
using MongoDB.Driver;
using MongoDB.Driver.Builders;
using System.Linq;
using FluentMongo.Linq;
using MongoDB.Bson.Serialization;


public class WebProfile : MongoProviders.User
{
    public static bool initialized = WebProfileMap.Register();

    public class WebProfileMap
    {
        public static bool Register()
        {
            if (!BsonClassMap.IsClassMapRegistered(typeof(WebProfile)))
            {
                MongoProviders.UserClassMap.Register();

                BsonClassMap.RegisterClassMap<WebProfile>(cm => 
                {
                    cm.AutoMap();
                    cm.SetIgnoreExtraElements(true);
                    cm.GetMemberMap(c => c.LastUpdatedDate).SetElementName("moddate");
                });
            }
            return true;
        }
    }
    
    public WebProfile()
    {
        Contacts = new ProfileContacts();
        Address = new ProfileAddress();
        Personal = new ProfilePersonal();
        Preferences = new ProfilePreferences();
    }

    public static WebProfile Get(string username)
    {
        var mongoMembership = (MongoProviders.MembershipProvider)Membership.Provider;
        var profiles = mongoMembership.Database.GetCollection<WebProfile>(mongoMembership.CollectionName);

        var profile = profiles.AsQueryable().Where(p => p.LowercaseUsername == username.ToLowerInvariant()).FirstOrDefault();
        return profile;
    }

    public virtual System.DateTime LastUpdatedDate { get; set; }
    
    public virtual ProfileContacts Contacts { get; set; }
    
    public virtual ProfileAddress Address { get; set; }
    
    public virtual ProfilePersonal Personal { get; set; }
   
    public virtual ProfilePreferences Preferences { get; set; }
    
    public virtual void Save() {

        var mongoMembership = (MongoProviders.MembershipProvider)Membership.Provider;
        var profiles = mongoMembership.Database.GetCollection<WebProfile>(mongoMembership.CollectionName);

        LastUpdatedDate = DateTime.UtcNow;
        profiles.Save(this);
    }
    
}


public class ProfileContacts {
    
    
    public ProfileContacts() { }
    
    public virtual string DayTimePhone { get; set; }
   
    public virtual string FaxHome { get; set; }

    public virtual string DayTimePhoneExt { get; set; }
    
    public virtual string EveningPhoneExt { get; set; }
   
    public virtual string EveningPhone { get; set; }
   
    public virtual string FaxBusiness { get; set; }

    public virtual string CellPhone { get; set; }
}

public class ProfileAddress {
    
    public ProfileAddress() { }
    
    public virtual string Country { get; set; }
    
    public virtual string City { get; set; }
    
    public virtual string State { get; set; }
    
    public virtual string Address { get; set; }
    
    public virtual string PostalCode { get; set; }
    
    public virtual string AptNumber { get; set; }
    
}

public class ProfilePersonal {
    
    public ProfilePersonal() { }
    
    public virtual string Occupation { get; set; }
    
    public virtual string Website { get; set; }
    
    public virtual string Gender { get; set; }
    
    public virtual System.DateTime BirthDate { get; set; }
    
    public virtual string LastName { get; set; }
    
    public virtual string FirstName { get; set; }
    
}

public class ProfilePreferences {
    
    public ProfilePreferences() { }
    
    public virtual string Culture { get; set; }
    
    public virtual string Theme { get; set; }
    
    public virtual string Newsletter { get; set; }
    
}
