//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Web;
using System.Web.Profile;
using System.Configuration;

/*
public class WebProfileGroupContacts {
    
    private System.Web.Profile.ProfileGroupBase _profileGroupBase;
    
    public WebProfileGroupContacts() {
        this._profileGroupBase = new System.Web.Profile.ProfileGroupBase();
    }
    
    public WebProfileGroupContacts(System.Web.Profile.ProfileGroupBase profileGroupBase) {
        this._profileGroupBase = profileGroupBase;
    }
    
    public virtual string DayTimePhone {
        get {
            return ((string)(this.GetPropertyValue("DayTimePhone")));
        }
        set {
            this.SetPropertyValue("DayTimePhone", value);
        }
    }
    
    public virtual string FaxHome {
        get {
            return ((string)(this.GetPropertyValue("FaxHome")));
        }
        set {
            this.SetPropertyValue("FaxHome", value);
        }
    }
    
    public virtual string DayTimePhoneExt {
        get {
            return ((string)(this.GetPropertyValue("DayTimePhoneExt")));
        }
        set {
            this.SetPropertyValue("DayTimePhoneExt", value);
        }
    }
    
    public virtual string EveningPhoneExt {
        get {
            return ((string)(this.GetPropertyValue("EveningPhoneExt")));
        }
        set {
            this.SetPropertyValue("EveningPhoneExt", value);
        }
    }
    
    public virtual string EveningPhone {
        get {
            return ((string)(this.GetPropertyValue("EveningPhone")));
        }
        set {
            this.SetPropertyValue("EveningPhone", value);
        }
    }
    
    public virtual string FaxBusiness {
        get {
            return ((string)(this.GetPropertyValue("FaxBusiness")));
        }
        set {
            this.SetPropertyValue("FaxBusiness", value);
        }
    }
    
    public virtual string CellPhone {
        get {
            return ((string)(this.GetPropertyValue("CellPhone")));
        }
        set {
            this.SetPropertyValue("CellPhone", value);
        }
    }
    
    public virtual System.Web.Profile.ProfileGroupBase ProfileGroupBase {
        get {
            return this._profileGroupBase;
        }
    }
    
    public virtual object this[string propertyName] {
        get {
            return this._profileGroupBase[propertyName];
        }
        set {
            this._profileGroupBase[propertyName] = value;
        }
    }
    
    public virtual object GetPropertyValue(string propertyName) {
        return this._profileGroupBase.GetPropertyValue(propertyName);
    }
    
    public virtual void SetPropertyValue(string propertyName, object propertyValue) {
        this._profileGroupBase.SetPropertyValue(propertyName, propertyValue);
    }
    
    public virtual void Init(System.Web.Profile.ProfileBase parent, string myName) {
        this._profileGroupBase.Init(parent, myName);
    }
}

public class WebProfileGroupAddress {
    
    private System.Web.Profile.ProfileGroupBase _profileGroupBase;
    
    public WebProfileGroupAddress() {
        this._profileGroupBase = new System.Web.Profile.ProfileGroupBase();
    }
    
    public WebProfileGroupAddress(System.Web.Profile.ProfileGroupBase profileGroupBase) {
        this._profileGroupBase = profileGroupBase;
    }
    
    public virtual string Country {
        get {
            return ((string)(this.GetPropertyValue("Country")));
        }
        set {
            this.SetPropertyValue("Country", value);
        }
    }
    
    public virtual string City {
        get {
            return ((string)(this.GetPropertyValue("City")));
        }
        set {
            this.SetPropertyValue("City", value);
        }
    }
    
    public virtual string State {
        get {
            return ((string)(this.GetPropertyValue("State")));
        }
        set {
            this.SetPropertyValue("State", value);
        }
    }
    
    public virtual string Address {
        get {
            return ((string)(this.GetPropertyValue("Address")));
        }
        set {
            this.SetPropertyValue("Address", value);
        }
    }
    
    public virtual string PostalCode {
        get {
            return ((string)(this.GetPropertyValue("PostalCode")));
        }
        set {
            this.SetPropertyValue("PostalCode", value);
        }
    }
    
    public virtual string AptNumber {
        get {
            return ((string)(this.GetPropertyValue("AptNumber")));
        }
        set {
            this.SetPropertyValue("AptNumber", value);
        }
    }
    
    public virtual System.Web.Profile.ProfileGroupBase ProfileGroupBase {
        get {
            return this._profileGroupBase;
        }
    }
    
    public virtual object this[string propertyName] {
        get {
            return this._profileGroupBase[propertyName];
        }
        set {
            this._profileGroupBase[propertyName] = value;
        }
    }
    
    public virtual object GetPropertyValue(string propertyName) {
        return this._profileGroupBase.GetPropertyValue(propertyName);
    }
    
    public virtual void SetPropertyValue(string propertyName, object propertyValue) {
        this._profileGroupBase.SetPropertyValue(propertyName, propertyValue);
    }
    
    public virtual void Init(System.Web.Profile.ProfileBase parent, string myName) {
        this._profileGroupBase.Init(parent, myName);
    }
}

public class WebProfileGroupPersonal {
    
    private System.Web.Profile.ProfileGroupBase _profileGroupBase;
    
    public WebProfileGroupPersonal() {
        this._profileGroupBase = new System.Web.Profile.ProfileGroupBase();
    }
    
    public WebProfileGroupPersonal(System.Web.Profile.ProfileGroupBase profileGroupBase) {
        this._profileGroupBase = profileGroupBase;
    }
    
    public virtual string Occupation {
        get {
            return ((string)(this.GetPropertyValue("Occupation")));
        }
        set {
            this.SetPropertyValue("Occupation", value);
        }
    }
    
    public virtual string Website {
        get {
            return ((string)(this.GetPropertyValue("Website")));
        }
        set {
            this.SetPropertyValue("Website", value);
        }
    }
    
    public virtual string Gender {
        get {
            return ((string)(this.GetPropertyValue("Gender")));
        }
        set {
            this.SetPropertyValue("Gender", value);
        }
    }
    
    public virtual System.DateTime BirthDate {
        get {
            return ((System.DateTime)(this.GetPropertyValue("BirthDate")));
        }
        set {
            this.SetPropertyValue("BirthDate", value);
        }
    }
    
    public virtual string LastName {
        get {
            return ((string)(this.GetPropertyValue("LastName")));
        }
        set {
            this.SetPropertyValue("LastName", value);
        }
    }
    
    public virtual string FirstName {
        get {
            return ((string)(this.GetPropertyValue("FirstName")));
        }
        set {
            this.SetPropertyValue("FirstName", value);
        }
    }
    
    public virtual System.Web.Profile.ProfileGroupBase ProfileGroupBase {
        get {
            return this._profileGroupBase;
        }
    }
    
    public virtual object this[string propertyName] {
        get {
            return this._profileGroupBase[propertyName];
        }
        set {
            this._profileGroupBase[propertyName] = value;
        }
    }
    
    public virtual object GetPropertyValue(string propertyName) {
        return this._profileGroupBase.GetPropertyValue(propertyName);
    }
    
    public virtual void SetPropertyValue(string propertyName, object propertyValue) {
        this._profileGroupBase.SetPropertyValue(propertyName, propertyValue);
    }
    
    public virtual void Init(System.Web.Profile.ProfileBase parent, string myName) {
        this._profileGroupBase.Init(parent, myName);
    }
}

public class WebProfileGroupPreferences {
    
    private System.Web.Profile.ProfileGroupBase _profileGroupBase;
    
    public WebProfileGroupPreferences() {
        this._profileGroupBase = new System.Web.Profile.ProfileGroupBase();
    }
    
    public WebProfileGroupPreferences(System.Web.Profile.ProfileGroupBase profileGroupBase) {
        this._profileGroupBase = profileGroupBase;
    }
    
    public virtual string Culture {
        get {
            return ((string)(this.GetPropertyValue("Culture")));
        }
        set {
            this.SetPropertyValue("Culture", value);
        }
    }
    
    public virtual string Theme {
        get {
            return ((string)(this.GetPropertyValue("Theme")));
        }
        set {
            this.SetPropertyValue("Theme", value);
        }
    }
    
    public virtual string Newsletter {
        get {
            return ((string)(this.GetPropertyValue("Newsletter")));
        }
        set {
            this.SetPropertyValue("Newsletter", value);
        }
    }
    
    public virtual System.Web.Profile.ProfileGroupBase ProfileGroupBase {
        get {
            return this._profileGroupBase;
        }
    }
    
    public virtual object this[string propertyName] {
        get {
            return this._profileGroupBase[propertyName];
        }
        set {
            this._profileGroupBase[propertyName] = value;
        }
    }
    
    public virtual object GetPropertyValue(string propertyName) {
        return this._profileGroupBase.GetPropertyValue(propertyName);
    }
    
    public virtual void SetPropertyValue(string propertyName, object propertyValue) {
        this._profileGroupBase.SetPropertyValue(propertyName, propertyValue);
    }
    
    public virtual void Init(System.Web.Profile.ProfileBase parent, string myName) {
        this._profileGroupBase.Init(parent, myName);
    }
}

public class WebProfile {
    
    private System.Web.Profile.ProfileBase _profileBase;
    
    public WebProfile() {
        this._profileBase = new System.Web.Profile.ProfileBase();
    }
    
    public WebProfile(System.Web.Profile.ProfileBase profileBase) {
        this._profileBase = profileBase;
    }
    
    public virtual WebProfileGroupContacts Contacts {
        get {
            return new WebProfileGroupContacts(this.GetProfileGroup("Contacts"));
        }
    }
    
    public virtual WebProfileGroupAddress Address {
        get {
            return new WebProfileGroupAddress(this.GetProfileGroup("Address"));
        }
    }
    
    public virtual WebProfileGroupPersonal Personal {
        get {
            return new WebProfileGroupPersonal(this.GetProfileGroup("Personal"));
        }
    }
    
    public virtual WebProfileGroupPreferences Preferences {
        get {
            return new WebProfileGroupPreferences(this.GetProfileGroup("Preferences"));
        }
    }
    
    public static WebProfile Current {
        get {
            return new WebProfile(System.Web.HttpContext.Current.Profile);
        }
    }
    
    public virtual System.Web.Profile.ProfileBase ProfileBase {
        get {
            return this._profileBase;
        }
    }
    
    public virtual object this[string propertyName] {
        get {
            return this._profileBase[propertyName];
        }
        set {
            this._profileBase[propertyName] = value;
        }
    }
    
    public virtual string UserName {
        get {
            return this._profileBase.UserName;
        }
    }
    
    public virtual bool IsAnonymous {
        get {
            return this._profileBase.IsAnonymous;
        }
    }
    
    public virtual bool IsDirty {
        get {
            return this._profileBase.IsDirty;
        }
    }
    
    public virtual System.DateTime LastActivityDate {
        get {
            return this._profileBase.LastActivityDate;
        }
    }
    
    public virtual System.DateTime LastUpdatedDate {
        get {
            return this._profileBase.LastUpdatedDate;
        }
    }
    
    public virtual System.Configuration.SettingsProviderCollection Providers {
        get {
            return this._profileBase.Providers;
        }
    }
    
    public virtual System.Configuration.SettingsPropertyValueCollection PropertyValues {
        get {
            return this._profileBase.PropertyValues;
        }
    }
    
    public virtual System.Configuration.SettingsContext Context {
        get {
            return this._profileBase.Context;
        }
    }
    
    public virtual bool IsSynchronized {
        get {
            return this._profileBase.IsSynchronized;
        }
    }
    
    public static System.Configuration.SettingsPropertyCollection Properties {
        get {
            return System.Web.Profile.ProfileBase.Properties;
        }
    }
    
    public virtual WebProfile GetProfile(string username) {
        return new WebProfile(System.Web.Profile.ProfileBase.Create(username));
    }
    
    public virtual object GetPropertyValue(string propertyName) {
        return this._profileBase.GetPropertyValue(propertyName);
    }
    
    public virtual void SetPropertyValue(string propertyName, object propertyValue) {
        this._profileBase.SetPropertyValue(propertyName, propertyValue);
    }
    
    public virtual System.Web.Profile.ProfileGroupBase GetProfileGroup(string groupName) {
        return this._profileBase.GetProfileGroup(groupName);
    }
    
    public virtual void Initialize(string username, bool isAuthenticated) {
        this._profileBase.Initialize(username, isAuthenticated);
    }
    
    public virtual void Save() {
        this._profileBase.Save();
    }
    
    public virtual void Initialize(System.Configuration.SettingsContext context, System.Configuration.SettingsPropertyCollection properties, System.Configuration.SettingsProviderCollection providers) {
        this._profileBase.Initialize(context, properties, providers);
    }
    
    public static System.Configuration.SettingsBase Synchronized(System.Configuration.SettingsBase settingsBase) {
        return System.Web.Profile.ProfileBase.Synchronized(settingsBase);
    }
    
    public static System.Web.Profile.ProfileBase Create(string userName) {
        return System.Web.Profile.ProfileBase.Create(userName);
    }
    
    public static System.Web.Profile.ProfileBase Create(string userName, bool isAuthenticated) {
        return System.Web.Profile.ProfileBase.Create(userName, isAuthenticated);
    }
}
*/